<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Silk.NET.Vulkan" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Vulkan.Extensions.KHR" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Vulkan.Extensions.EXT" Version="2.23.0" />

    <PackageVersion Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageVersion Include="Vortice.DXGI" Version="3.8.3" />
    <PackageVersion Include="Vortice.Mathematics" Version="2.1.1" />

    <PackageVersion Include="SkiaSharp" Version="3.119.4" />
  </ItemGroup>
</Project>