<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <MediaForgeNdiWindowsRuntimeRoot Condition="'$(MediaForgeNdiWindowsRuntimeRoot)' == ''">$(MSBuildThisFileDirectory)..\third_party\ndi\windows</MediaForgeNdiWindowsRuntimeRoot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="Vortice.Direct3D11" />
    <PackageReference Include="Vortice.DXGI" />
    <PackageReference Include="Vortice.MediaFoundation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WTK.MediaForge.Capture\WTK.MediaForge.Capture.csproj" />
    <ProjectReference Include="..\WTK.MediaForge.Composition\WTK.MediaForge.Composition.csproj" />
    <ProjectReference Include="..\WTK.MediaForge.Core\WTK.MediaForge.Core.csproj" />
    <ProjectReference Include="..\WTK.MediaForge.Diagnostics\WTK.MediaForge.Diagnostics.csproj" />
    <ProjectReference Include="..\WTK.MediaForge.Graphics.D3D11\WTK.MediaForge.Graphics.D3D11.csproj" />
    <ProjectReference Include="..\WTK.MediaForge.Graphics.Vulkan\WTK.MediaForge.Graphics.Vulkan.csproj" />
  </ItemGroup>

  <ItemGroup Condition="Exists('$(MediaForgeNdiWindowsRuntimeRoot)\x64\Processing.NDI.Lib.x64.dll')">
    <None Include="$(MediaForgeNdiWindowsRuntimeRoot)\x64\Processing.NDI.Lib.x64.dll"
          Link="runtimes\win-x64\native\Processing.NDI.Lib.x64.dll"
          CopyToOutputDirectory="PreserveNewest"
          Pack="true"
          PackagePath="runtimes\win-x64\native\Processing.NDI.Lib.x64.dll" />
  </ItemGroup>

  <ItemGroup Condition="Exists('$(MediaForgeNdiWindowsRuntimeRoot)\x86\Processing.NDI.Lib.x86.dll')">
    <None Include="$(MediaForgeNdiWindowsRuntimeRoot)\x86\Processing.NDI.Lib.x86.dll"
          Link="runtimes\win-x86\native\Processing.NDI.Lib.x86.dll"
          CopyToOutputDirectory="PreserveNewest"
          Pack="true"
          PackagePath="runtimes\win-x86\native\Processing.NDI.Lib.x86.dll" />
  </ItemGroup>

</Project>
