<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <ProjectReference Include="..\WTK.MediaForge.Remote\WTK.MediaForge.Remote.csproj" />
  </ItemGroup>
</Project>
