<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D11" />
    <PackageReference Include="Vortice.DXGI" />
    <PackageReference Include="Vortice.Mathematics" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WTK.MediaForge.Core\WTK.MediaForge.Core.csproj" />
    <ProjectReference Include="..\WTK.MediaForge.Diagnostics\WTK.MediaForge.Diagnostics.csproj" />
  </ItemGroup>

</Project>
