<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WTK.MediaForge.Core.Tests" />
    <InternalsVisibleTo Include="WTK.MediaForge.Composition.Tests" />
    <InternalsVisibleTo Include="WTK.MediaForge.Composition" />
    <InternalsVisibleTo Include="WTK.MediaForge.Capture.Tests" />
    <InternalsVisibleTo Include="WTK.MediaForge.Capture" />
    <InternalsVisibleTo Include="WTK.MediaForge.Graphics.Vulkan.Tests" />
    <InternalsVisibleTo Include="WTK.MediaForge.Windows" />
    <InternalsVisibleTo Include="WTK.MediaForge.Windows.Tests" />
  </ItemGroup>

</Project>
