<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Shaderc" />
    <PackageReference Include="Silk.NET.Vulkan" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.EXT" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Shaders\desktop_preview.vert" />
    <EmbeddedResource Include="Shaders\desktop_preview.frag" />
    <EmbeddedResource Include="Shaders\Catalog\mf_common.vert" />
    <EmbeddedResource Include="Shaders\Catalog\mf_source_layer.frag" />
    <EmbeddedResource Include="Shaders\Catalog\mf_solid.frag" />
    <EmbeddedResource Include="Shaders\Catalog\mf_text.frag" />
    <EmbeddedResource Include="Shaders\Catalog\mf_canvas_composite.frag" />
    <EmbeddedResource Include="Shaders\Catalog\mf_output_letterbox.frag" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WTK.MediaForge.Composition\WTK.MediaForge.Composition.csproj" />
    <ProjectReference Include="..\WTK.MediaForge.Core\WTK.MediaForge.Core.csproj" />
    <ProjectReference Include="..\WTK.MediaForge.Diagnostics\WTK.MediaForge.Diagnostics.csproj" />
  </ItemGroup>

</Project>
